"""Tests for issue #12: probe_blocked first-class classification.

A 403 from an identifiable CDN/WAF edge box short-circuits the pipeline
into a synthetic ``probe_blocked`` result: vendor fingerprint as
subcategory, no Claude call, no further requests to the host that just
blocked us. An unidentified 403 falls through to the normal pipeline.
"""

from __future__ import annotations

import json
from dataclasses import dataclass

import httpx
import pytest
import respx

from cartograph_ai import ProbeOptions, probe
from cartograph_ai.stages.http_probe import detect_waf_block, probe_http


# ---------------- Stubs --------------------------------------------------


@dataclass
class StubUsage:
    input_tokens: int = 0
    output_tokens: int = 0


@dataclass
class StubTextBlock:
    type: str = "text"
    text: str = ""


@dataclass
class StubMessage:
    content: list
    model: str = "claude-sonnet-4-6"
    usage: StubUsage = None

    def __post_init__(self):
        if self.usage is None:
            self.usage = StubUsage(input_tokens=1500, output_tokens=300)


class StubMessagesEndpoint:
    def __init__(self, response: StubMessage):
        self.response = response
        self.calls = []

    def create(self, **kwargs):
        self.calls.append(kwargs)
        return self.response


class StubAnthropic:
    def __init__(self, response: StubMessage):
        self.messages = StubMessagesEndpoint(response)


AKAMAI_BLOCK_BODY = (
    "<HTML><HEAD><TITLE>Access Denied</TITLE></HEAD><BODY>"
    "You don't have permission to access this resource. "
    'Reference&#32;#18.5d4d1502.1717777777.1a2b3c4 '
    "</BODY></HTML>"
)

CLOUDFRONT_BLOCK_BODY = (
    "<html><body><h1>403 ERROR</h1><p>The request could not be satisfied.</p>"
    "Generated by cloudfront (CloudFront)</body></html>"
)


# ---------------- detect_waf_block unit tests ----------------------------


def test_detect_akamai_from_server_header():
    block = detect_waf_block(
        403, httpx.Headers({"server": "AkamaiGHost"}), "Access Denied"
    )
    assert block is not None
    assert block["vendor"] == "akamai_ghost"
    assert any("server header" in e for e in block["evidence"])


def test_detect_akamai_from_reference_body():
    block = detect_waf_block(403, httpx.Headers({}), AKAMAI_BLOCK_BODY)
    assert block is not None
    assert block["vendor"] == "akamai_ghost"


def test_detect_cloudfront():
    block = detect_waf_block(
        403,
        httpx.Headers({"server": "CloudFront", "x-amz-cf-id": "abc123=="}),
        CLOUDFRONT_BLOCK_BODY,
    )
    assert block is not None
    assert block["vendor"] == "cloudfront"


def test_cf_headers_alone_with_json_error_body_is_not_a_block():
    """x-amz-cf-* headers ride on every CloudFront response, including
    legitimate keyed-API 403s. A JSON error body is the API answering, not
    the edge blocking it (issue #23 / Run 03 Finding 2). Must not become a
    probe_blocked false positive on the kill-metric surface."""
    block = detect_waf_block(
        403,
        httpx.Headers(
            {"x-amz-cf-id": "abc==", "content-type": "application/json"}
        ),
        '{"errors":[{"status":"403","title":"API_KEY_MISSING"}]}',
    )
    assert block is None


def test_cf_json_body_without_content_type_is_not_a_block():
    """A body that parses as JSON is an application answering even when the
    content-type header is absent or generic; still not an edge block."""
    block = detect_waf_block(
        403,
        httpx.Headers({"x-amz-cf-pop": "IAD89-C1"}),
        '{"errors":[{"detail":"over rate limit"}]}',
    )
    assert block is None


def test_detect_aws_waf_elb():
    block = detect_waf_block(
        403, httpx.Headers({"server": "awselb/2.0"}), ""
    )
    assert block is not None
    assert block["vendor"] == "aws_waf_elb"


def test_detect_cloudflare():
    block = detect_waf_block(
        403,
        httpx.Headers({"server": "cloudflare", "cf-ray": "8f00ba11-EWR"}),
        "<title>Attention Required! | Cloudflare</title>",
    )
    assert block is not None
    assert block["vendor"] == "cloudflare"


def test_non_403_is_never_a_block():
    assert detect_waf_block(200, httpx.Headers({"server": "AkamaiGHost"}), "") is None
    assert detect_waf_block(503, httpx.Headers({"server": "AkamaiGHost"}), "") is None
    assert detect_waf_block(None, httpx.Headers({}), "") is None


def test_unidentified_403_is_not_a_block():
    """A content-layer 403 (nginx, no vendor fingerprint) falls through."""
    block = detect_waf_block(
        403, httpx.Headers({"server": "nginx"}), "<h1>Forbidden</h1>"
    )
    assert block is None


def test_cf_headers_alone_on_403_count_as_cloudfront():
    """x-amz-cf-* headers identify CloudFront even without a Server header."""
    block = detect_waf_block(
        403, httpx.Headers({"x-amz-cf-pop": "IAD89-C1"}), "403 forbidden"
    )
    assert block is not None
    assert block["vendor"] == "cloudfront"


# ---------------- Stage 1 integration ------------------------------------


@respx.mock
def test_probe_http_stops_after_identified_block():
    """On a positive vendor identification, robots/sitemaps are not fetched."""
    respx.get("https://www.nhtsa.gov/").mock(
        return_value=httpx.Response(
            403, content=AKAMAI_BLOCK_BODY, headers={"server": "AkamaiGHost"}
        )
    )
    robots = respx.get("https://www.nhtsa.gov/robots.txt").mock(
        return_value=httpx.Response(404)
    )

    findings = probe_http("https://www.nhtsa.gov/", polite_delay=0.0)

    assert findings["waf_block"] is not None
    assert findings["waf_block"]["vendor"] == "akamai_ghost"
    assert findings["status"] == 403
    assert findings["error"] is None
    assert not robots.called
    assert findings["robots_txt"] == {"present": False}
    assert findings["sitemaps"] == []


@respx.mock
def test_probe_http_unidentified_403_continues():
    respx.get("https://example.com/").mock(
        return_value=httpx.Response(
            403, content="<h1>Forbidden</h1>", headers={"server": "nginx"}
        )
    )
    robots = respx.get("https://example.com/robots.txt").mock(
        return_value=httpx.Response(404)
    )
    respx.get("https://example.com/sitemap.xml").mock(return_value=httpx.Response(404))
    respx.get("https://example.com/sitemap_index.xml").mock(
        return_value=httpx.Response(404)
    )

    findings = probe_http("https://example.com/", polite_delay=0.0)

    assert findings["waf_block"] is None
    assert robots.called


# ---------------- Orchestrator integration -------------------------------


def _mock_blocked_site(url_root: str, *, headers: dict, body: str) -> None:
    respx.get(url_root).mock(
        return_value=httpx.Response(403, content=body, headers=headers)
    )


@respx.mock
def test_probe_returns_probe_blocked_without_claude_call():
    _mock_blocked_site(
        "https://www.nhtsa.gov/",
        headers={"server": "AkamaiGHost"},
        body=AKAMAI_BLOCK_BODY,
    )

    client = StubAnthropic(StubMessage(content=[StubTextBlock(text="{}")]))
    http_client = httpx.Client(follow_redirects=True, timeout=5.0)
    try:
        result = probe(
            "https://www.nhtsa.gov/",
            anthropic_client=client,
            http_client=http_client,
            options=ProbeOptions(preflight_key_check=False, polite_delay=0.0),
        )
    finally:
        http_client.close()

    assert result.classification.category == "probe_blocked"
    assert result.classification.subcategory == "akamai_ghost"
    assert result.classification.confidence == 0.9
    assert result.model == "none (stage 4 not reached)"
    assert client.messages.calls == []  # no Claude call, $0
    assert result.probe_stages_completed == ["http"]
    assert "claude_classify" in result.probe_stages_skipped
    assert result.extraction_strategy.specifics["vendor"] == "akamai_ghost"
    assert result.extraction_strategy.specifics["block_layer"] == "cdn_edge"
    assert result.low_confidence_warning is False
    assert result.limitations  # honest network-edge report present


@respx.mock
def test_probe_blocked_is_json_serialisable_and_distinct_from_unknown():
    _mock_blocked_site(
        "https://www.regulations.gov/",
        headers={"server": "CloudFront", "x-amz-cf-id": "zzz"},
        body=CLOUDFRONT_BLOCK_BODY,
    )

    client = StubAnthropic(StubMessage(content=[StubTextBlock(text="{}")]))
    http_client = httpx.Client(follow_redirects=True, timeout=5.0)
    try:
        result = probe(
            "https://www.regulations.gov/",
            anthropic_client=client,
            http_client=http_client,
            options=ProbeOptions(preflight_key_check=False, polite_delay=0.0),
        )
    finally:
        http_client.close()

    payload = json.loads(result.model_dump_json())
    assert payload["classification"]["category"] == "probe_blocked"
    assert payload["classification"]["category"] != "unknown"
    assert payload["classification"]["subcategory"] == "cloudfront"


@respx.mock
def test_probe_blocked_passes_strict_mode():
    """probe_blocked is a definitive, evidence-backed classification.

    Unlike probe_unreachable (0.0 confidence, nothing learned), a
    vendor-identified block is actionable intelligence; strict mode
    returns it rather than raising.
    """
    _mock_blocked_site(
        "https://filingaccess.serff.com/",
        headers={"server": "awselb/2.0"},
        body="",
    )

    client = StubAnthropic(StubMessage(content=[StubTextBlock(text="{}")]))
    http_client = httpx.Client(follow_redirects=True, timeout=5.0)
    try:
        result = probe(
            "https://filingaccess.serff.com/",
            anthropic_client=client,
            http_client=http_client,
            options=ProbeOptions(
                strict=True, preflight_key_check=False, polite_delay=0.0
            ),
        )
    finally:
        http_client.close()

    assert result.classification.category == "probe_blocked"
    assert result.classification.subcategory == "aws_waf_elb"
